version: '1.0'

services:

  mq-client-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - IBM_MQ_CONN_NAME=mqserver(1414)
    depends_on:
      - "mqserver"

    # browse to: https://localhost:9443/ibmmq/console/
  mqseries:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    container_name: mqserver
    stdin_open: true
    tty: true
    restart: always
